better now

diff --git a/config/std_functions b/config/std_functions
--- a/config/std_functions
+++ b/config/std_functions
@@ -1,21 +1,39 @@
 #!/usr/bin/env bash
 runcron(){ 
-	php /var/www/*/cron/cronRunner.php /var/www/*/cron/.. /var/www/*/cron/jobs/$1.php /var/www/*/*/$2{,admin}.php 1320168191 || echo "ERROR"
+	if [ -f /var/www/*/*/$2admin.php ] ; then
+		php /var/www/*/cron/cronRunner.php /var/www/*/cron/.. /var/www/*/cron/jobs/$1.php /var/www/*/*/$2admin.php 1320168191 || echo "ERROR"
+	else
+		php /var/www/*/cron/cronRunner.php /var/www/*/cron/.. /var/www/*/cron/jobs/$1.php /var/www/*/*/$2.php 1320168191 || echo "ERROR"
+	fi
 }
 
 lesslog(){
-	if [[ "$3" == "" ]] ; then
-		less /var/www/*/cron/log/$1/$(date +%Y-%m-%d)/$2{,admin}.log
+	local inst
+	if [ -f /var/www/*/*/$2admin.php ] ; then
+		inst=$2admin.log
 	else
-		less /var/www/*/cron/log/$1/$3/$2{,admin}.log
+		inst=$2.log
+	fi
+
+	if [[ "$3" == "" ]] ; then
+		less /var/www/*/cron/log/$1/$(date +%Y-%m-%d)/$inst
+	else
+		less /var/www/*/cron/log/$1/$3/$inst
 	fi
 }
 
 taillog(){
-	if [[ "$3" == "" ]] ; then
-		tail -f -n10000 /var/www/*/cron/log/$1/$(date +%Y-%m-%d)/$2{,admin}.log
+	local inst
+	if [ -f /var/www/*/*/$2admin.php ] ; then
+		inst=$2admin.log
 	else
-		tail -f -n10000 /var/www/*/cron/log/$1/$3/$2{,admin}.log
+		inst=$2.log
+	fi
+	
+	if [[ "$3" == "" ]] ; then
+		tail -f -n10000 /var/www/*/cron/log/$1/$(date +%Y-%m-%d)/$inst
+	else
+		tail -f -n10000 /var/www/*/cron/log/$1/$3/$inst
 	fi
 }
 
