added unison 2.40

diff --git a/config/std_functions b/config/std_functions
--- a/config/std_functions
+++ b/config/std_functions
@@ -1,21 +1,21 @@
 #!/usr/bin/env bash
 runcron(){ 
-	php /var/www/*/cron/cronRunner.php /var/www/*/cron/.. /var/www/*/cron/jobs/$1.php /var/www/*/*/$2admin.php 1320168191 || echo "ERROR"
+	php /var/www/*/cron/cronRunner.php /var/www/*/cron/.. /var/www/*/cron/jobs/$1.php /var/www/*/*/$2{,admin}.php 1320168191 || echo "ERROR"
 }
 
 lesslog(){
 	if [[ "$3" == "" ]] ; then
-		less /var/www/*/cron/log/$1/$(date +%Y-%m-%d)/$2*.log
+		less /var/www/*/cron/log/$1/$(date +%Y-%m-%d)/$2{,admin}.log
 	else
-		less /var/www/*/cron/log/$1/$3/$2*.log
+		less /var/www/*/cron/log/$1/$3/$2{,admin}.log
 	fi
 }
 
 taillog(){
 	if [[ "$3" == "" ]] ; then
-		tail -f -n10000 /var/www/*/cron/log/$1/$(date +%Y-%m-%d)/$2*.log
+		tail -f -n10000 /var/www/*/cron/log/$1/$(date +%Y-%m-%d)/$2{,admin}.log
 	else
-		tail -f -n10000 /var/www/*/cron/log/$1/$3/$2*.log
+		tail -f -n10000 /var/www/*/cron/log/$1/$3/$2{,admin}.log
 	fi
 }
 
